import { Centro, Categoria, Servicio } from './interfaces';

export const CENTROS: Centro[] = [
  { id: '0', name: 'Centro Internacional' },
  { id: '1', name: 'Escuela Internacional de Postgrado' },
  { id: '2', name: 'Escuela Técnica Superior de Ingeniería' },
  { id: '3', name: 'Escuela Técnica Superior de Ingeniería Informática' },
  { id: '4', name: 'Facultad de Ciencias de la Educación' },
  { id: '5', name: 'Facultad de Comunicación' },
  { id: '6', name: 'Facultad de Derecho' },
  { id: '7', name: 'Facultad de Enfermería, Fisioterapia y Podología' },
  { id: '8', name: 'Facultad de Filología' },
  { id: '9', name: 'Facultad de Geografía e Historia' },
  { id: '10', name: 'Facultad de Medicina' },
  { id: '11', name: 'Facultad de Psicología' },
  { id: '12', name: 'Instituto de Idiomas' },
  { id: '13', name: 'Secretariado de Prácticas en Empresa y Empleo' },
];

export const CATEGORIAS: Categoria[] = [
  { id: '0', name: 'Otras Solicitudes' },
  { id: '1', name: 'Ampliación de Matrícula' },
  { id: '2', name: 'Prácticas en Empresas' },
  { id: '3', name: 'Información' },
  { id: '4', name: 'Reconocimientos de Créditos' },
  { id: '5', name: 'Compulsas' },
  { id: '6', name: 'Traslados de Expediente' },
  { id: '7', name: 'Títulos' },
  { id: '8', name: 'Matriculación' },
  { id: '9', name: 'Certificaciones' },
];

export const SERVICIOS: Servicio[] = [
  { id: '0', categoriaId: '0', name: 'Presentación de otras solicitudes' },
  { id: '1', categoriaId: '0', name: 'Presentación de solicitud de devolución' },
  { id: '2', categoriaId: '0', name: 'Presentación solicitud cambio Departamento Proyecto' },
  { id: '3', categoriaId: '1', name: 'Presentación de solicitud de ampliación de matrícula' },
  { id: '4', categoriaId: '1', name: 'Recogida carta de pago ampliación matrícula' },
  { id: '5', categoriaId: '2', name: 'Presentación de solicitud de prácticas' },
  { id: '6', categoriaId: '3', name: 'Información general' },
  { id: '7', categoriaId: '4', name: 'Entrega de documentación de reconocimiento de créditos' },
  { id: '8', categoriaId: '4', name: 'Información sobre reconocimientos y adaptaciones' },
  { id: '9', categoriaId: '4', name: 'Presentación de solicitud de reconocimiento de créditos' },
  { id: '10', categoriaId: '5', name: 'Compulsa de documentos' },
  { id: '11', categoriaId: '6', name: 'Entrega de traslado de expediente' },
  { id: '12', categoriaId: '6', name: 'Presentación de solicitud de traslado de expediente' },
  { id: '13', categoriaId: '7', name: 'Presentación de solicitud de título' },
  { id: '14', categoriaId: '7', name: 'Recogida del resguardo de Título' },
  { id: '15', categoriaId: '7', name: 'Recogida del título' },
  { id: '16', categoriaId: '8', name: 'Compulsa y revisión de matrículas' },
  { id: '17', categoriaId: '8', name: 'Información sobre matrícula' },
  { id: '18', categoriaId: '8', name: 'Presentación de solicitud de anulación de matrícula' },
  { id: '19', categoriaId: '8', name: 'Presentación de solicitud de cambio de grupo inglés' },
  { id: '20', categoriaId: '8', name: 'Presentación de solicitud de modificación de matrícula' },
  { id: '21', categoriaId: '8', name: 'Presentación de solicitud de permuta' },
  { id: '22', categoriaId: '8', name: 'Presentación solicitud matrícula Prácticas en Empresas' },
  { id: '23', categoriaId: '9', name: 'Recogida de Certificaciones Académicas' },
  { id: '24', categoriaId: '9', name: 'Solicitud de certificaciones académicas' },
];
